networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/logistic
    depends_on:
      - pgsql
      - php
      - redis
    networks:
      - app-network

  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/logistic
    networks:
      - app-network

  pgsql:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - .docker/volume/pgsql/data:/var/lib/postgresql/data
      - .docker/volume/pgsql/sql:/docker-entrypoint-initdb.d
    env_file:
      - env/pgsql.env
    networks:
      - app-network

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/volume/redis/data:/data
    ports:
      - 6379:6379
    networks:
      - app-network